### PR TITLE
Error codes are slightly better now

### PR DESCRIPTION
**Pull request by LNLenost**

### CODE REVIEW

**Comment by walterwhite1337** [comment]
Please join the discord server

**Comment by trlandrew** [comment]
The error pages are supposed to be the same from  https://nsc.ftolnks.xyz. I won't merge this.

**Comment by LNLenost** [comment]
> The error pages are supposed to be the same from  https://nsc.ftolnks.xyz. I won't merge this.

Oops, ok

**Comment by LNLenost** [comment]
> Please join the discord server

...

I can join it with my dad's account but I use it rarely.

**Pull request closed without merging**
