### PR TITLE
Moved every English file inside translations (else Crowdin wont work)

### PR DESCRIPTION
**Pull request by LNLenost**

### CODE REVIEW

**Comment by walterwhite1337** [comment]
...

**Comment by walterwhite1337** [comment]
It shows "delete"

**Comment by LNLenost** [comment]
> It shows "delete"

They are now in translations/en

**Comment by walterwhite1337** [comment]
K.

**Comment by LNLenost** [comment]
I may have translated too much... 💀

**Comment by trlandrew** [comment]
wtf man 252 commits

**Pull request merged**
