### PR TITLE
translate error pages (it)

### PR DESCRIPTION
**Pull request by idkwhereisthisname**

### CODE REVIEW

**Comment by idkwhereisthisname** [comment]
btw these arent on crowdin so i decided to put this here

**Comment by LNLenost** [comment]
Thanks! It's somewhat difficult to add them.

**Comment by LNLenost** [comment]
Hold up, I managed to get it running on Crowdin. It should be online now. Thanks tho!

**Comment by trlandrew** [comment]
error pages can't be translated so this pull request is denied

**Pull request closed without merging**
