### PR TITLE
Added gallery

### PR DESCRIPTION
**Pull request by LNLenost**
The button works in the homepage too.

### CODE REVIEW

**Comment by trlandrew** [comment]
I'll check later.

**Comment by LNLenost** [comment]
👍

**Comment by walterwhite1337** [comment]
LGTM!!!! forward it to finfinfin

**Comment by LNLenost** [comment]
> LGTM!!!! forward it to finfinfin

whats his user?

**Comment by LNLenost** [comment]
WOOOOOO just managed to get VSC working

**Comment by trlandrew** [comment]
ok its good

**Comment by LNLenost** [comment]
> ok its good

Yayyy tysm

**Pull request merged**
