### PR TITLE
Crowdin + request (read desc)

### PR DESCRIPTION
**Pull request by LNLenost**
What if we set the Crowdin directly on the rep? I need write access though

### CODE REVIEW

**Comment by trlandrew** [comment]
wdym "directly on the repo" also you know that those index.php and gallery.php files were important and you literally just removed them

**Comment by LNLenost** [comment]
> wdym "directly on the repo" also you know that those index.php and gallery.php files were important and you literally just removed them

??? Hold up ill check

**Comment by LNLenost** [comment]
No? They are inside translations/en

**Comment by LNLenost** [comment]
> wdym "directly on the repo" also you know that those index.php and gallery.php files were important and you literally just removed them

Also dont worry about the write access, ill just use PRs

**Comment by LNLenost** [comment]
> wdym "directly on the repo" also you know that those index.php and gallery.php files were important and you literally just removed them

If you cant see the files I just downloaded them.

**Comment by trlandrew** [comment]
you really did not understand what I meant by root... right? that's where the readme.md and license is, and there were files that were needed. go try hosting the source code and wonder why it shows me a bunch of folders instead of the index page

**Comment by LNLenost** [comment]
> you really did not understand what I meant by root... right? that's where the readme.md and license is, and there were files that were needed. go try hosting the source code and wonder why it shows me a bunch of folders instead of the index page

Sorry dude :((( im incredibly stupid

Added them back to the root

**Comment by LNLenost** [comment]
New translations!

**Pull request merged**
