### PR TITLE
Added new wallpapers and GitHub page (read desc!)

### PR DESCRIPTION
**Pull request by LNLenost**
So I added a github.html page and the button inside index.html, BUT I'm not sure the button works. Pls anyone check it out

### CODE REVIEW

**Comment by trlandrew** [comment]
I don't think we need a GitHub page just for a link, because we could just make an alert with a link to the repository. Also we don't need classes like dscontent and dslink.

**Comment by LNLenost** [comment]
I put it so people wont ask "whEre IS tHe sOUrcE cOdE??!?!?!"

**Comment by trlandrew** [comment]
Just make a Bootstrap-like alert with the link. That's it.

**Comment by LNLenost** [comment]
> Also we don't need classes like dscontent and dslink.

Removed

**Comment by LNLenost** [comment]
> Just make a Bootstrap-like alert with the link. That's it.

Srry I dont know what that is :(

**Pull request merged**
