### PR TITLE
New Crowdin updates

### PR DESCRIPTION
**Pull request by LNLenost**

### CODE REVIEW

**Comment by LNLenost** [comment]
With "write access" i meant this btw: https://docs.github.com/en/account-and-profile/setting-up-and-managing-your-personal-account-on-github/managing-access-to-your-personal-repositories/inviting-collaborators-to-a-personal-repository

So Crowdin goes directly to this rep and not on mine (aka u dont have to accept my PRs because Crowdin will do that automatically)

**Comment by trlandrew** [comment]
oh

**Comment by trlandrew** [comment]
I won't give you write access but I'll do what you want me to for this crowdin stuff

**Comment by LNLenost** [comment]
> I won't give you write access but I'll do what you want me to for this crowdin stuff

Nah its fine, ill use PRs

**Review by LNLenost — COMMENTED** [review]
How many commits have you made?
Me:

**Pull request merged**
