### PR TITLE
Add Discord page

### PR DESCRIPTION
**Pull request by walterwhite1337**
Added discord page with the link to the discord server.

### CODE REVIEW

**Comment by trlandrew** [comment]
wait till this person realizes the Wii can't open Discord

**Comment by walterwhite1337** [comment]
> wait till this person realizes the Wii can't open Discord

It literally says "open on another device"

**Comment by walterwhite1337** [comment]
> It literally says "open on another device"

And the link is not clickable.

**Comment by trlandrew** [comment]
oh

**Comment by LNLenost** [comment]
> wait till this person realizes the Wii can't open Discord

Discross

**Pull request merged**
